### ISSUE TITLE
How can i change segment with images like whatsapp?

### ISSUE THREAD

**Issue by bintu1234** [ayushgoel/AGEmojiKeyboard#14]
Hi How can i change emoji segment with images i want to use like whatsapp images instead of segment please can any body done that?(I'm not talking about the emoji images only segment )

**Comment by ayushgoel** [comment]
You need to implement [emojiKeyboardView:imageForSelectedCategory:](http://cocoadocs.org/docsets/AGEmojiKeyboard/0.2.0/Protocols/AGEmojiKeyboardViewDataSource.html#//api/name/emojiKeyboardView:imageForSelectedCategory:) and [emojiKeyboardView:imageForNonSelectedCategory:](http://cocoadocs.org/docsets/AGEmojiKeyboard/0.2.0/Protocols/AGEmojiKeyboardViewDataSource.html#//api/name/emojiKeyboardView:imageForNonSelectedCategory:).

**Comment by bintu1234** [comment]
@ayushgoel Thanks for replay i tried above methods but which is not showing any image when i use above mehods

**Comment by ayushgoel** [comment]
Can you please show the code you are using?

**Comment by bintu1234** [comment]
- (UIImage *)emojiKeyboardView:(AGEmojiKeyboardView *)emojiKeyboardView imageForSelectedCategory:(AGEmojiKeyboardViewCategoryImage)category {
    UIImage *img=[UIImage imageNamed:@"broad"];
    [img imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal];
    return img;
}

**Comment by bintu1234** [comment]
instead of random image i am just taken my own image but it is not showing as segment image please help me

**Comment by ayushgoel** [comment]
@bintu1234 Check the Example project in the repo, especially this [file](https://github.com/ayushgoel/AGEmojiKeyboard/blob/master/Example%2FAGEmojiKeyboardSample%2FAGViewController.m). Hope it helps.

**Comment by ayushgoel** [comment]
Closing this as no followup.

**Comment by bintu1234** [comment]
@ayushgoel  Thanks it's working fine now.
