### ISSUE TITLE
Do you have solution for stickers

### ISSUE THREAD

**Issue by satyamub** [ayushgoel/AGEmojiKeyboard#15]
Have you implemented the sticker concept in emoji keyboard where one can provide its own image?

**Comment by ayushgoel** [comment]
In short: No. But you can open a Pull Request if you want to. I would be more than happy to have it here.

**Comment by satyamub** [comment]
Bro One more thing I wanted to ask, I have seen that the keyboard has images of categories and in this example, it does not show that instead it shows blue line. What for?

**Comment by ayushgoel** [comment]
The category images are to be provided by the user of the keyboard.

Check the [AGEmojiKeyboardViewDataSource](https://github.com/ayushgoel/AGEmojiKeyboard/blob/master/AGEmojiKeyboard/AGEmojiKeyBoardView.h#L67) protocol on how to do it.

**Comment by ayushgoel** [comment]
Closing as resolved.
