### ISSUE TITLE
Three more features

### ISSUE THREAD

**Issue by sdtaheri** [ayushgoel/AGEmojiKeyboard#5]
Hi,

This is a great project. I really appreciate.
I just want to ask you for some little things. I worked on them a lot but many unexpected issues arise.

1. The ability to remove the pageControl dots.
2. The ability to move the segmented control to the bottom of the keyboard.
3. The ability to remove the backspace from each page and move it besides the segmented control since I want to turn pagingEnabled off. (a la iOS 8.3 emoji keyboard)
4. The ability to move between each segment by scrolling. I mean when each category ends, I can continue swiping to next category. (a la Notification Center in iOS)

I hope you could help me with at least item 1 to item 3.

Best regards,
Saeed Taheri

**Comment by ayushgoel** [comment]
Hey sdtaheri,

Thank you for the appreciation.

For all the items, you can [fork](https://guides.github.com/activities/forking/) this repository and make changes to [AGEmojiKeyBoardView.m](https://github.com/ayushgoel/AGEmojiKeyboard/blob/master/AGEmojiKeyboard%2FAGEmojiKeyBoardView.m). I don't think the current interface of the keyboard can give you what you want.

Cheers!
Ayush
