### ISSUE TITLE
this can use autolayout?

### ISSUE THREAD

**Issue by xiaoyangh** [ayushgoel/AGEmojiKeyboard#6]
hi,this can use auto layout

**Comment by ayushgoel** [comment]
Yes, it surely can.
Though, you might have to handle rotation. The number of buttons shown changes when orientation changes.
If you are interested, [fork](https://guides.github.com/activities/forking/#fork) this project and open a [pull request](https://guides.github.com/activities/forking/#making-a-pull-request) when you are done.
