### ISSUE TITLE
library not found for -lPods-AGEmojiKeyboard

### ISSUE THREAD

**Issue by sauchye** [ayushgoel/AGEmojiKeyboard#8]
when i remove AGEmojiKeyboard in Podfile,run my project,show:library not found for -lPods-AGEmojiKeyboard

**Comment by ayushgoel** [comment]
This issue seems to be related to usage of Cocoapods. Better to ask it on stackoverflow.com

This is what I found in my research, hope it helps.. http://stackoverflow.com/questions/9863836/library-not-found-for-lpods/24341086

**Comment by sauchye** [comment]
thanks ayushgoel
