### ISSUE TITLE
category image doesn't show

### ISSUE THREAD

**Issue by caofei10119** [ayushgoel/AGEmojiKeyboard#9]
I returned different images for the category in datasource but it shows only blue round button.

**Comment by ayushgoel** [comment]
Can you show the code where you are returning the image.

Check the sample project for example if you are missing something. Hope it helps.
https://github.com/ayushgoel/AGEmojiKeyboard/blob/fb5f030d76351411155983ff5313e666c83fa90c/Example/AGEmojiKeyboardSample/AGViewController.m#L71

**Comment by ayushgoel** [comment]
Closing as not enough data.
